steps:
- name: 'nikolaik/python-nodejs:python3.7-nodejs10-alpine'
  args: ['python', './scripts/csvToJson.py']

- name: 'nikolaik/python-nodejs:python3.7-nodejs10-alpine'
  args: ['npm', 'install']

- name: 'nikolaik/python-nodejs:python3.7-nodejs10-alpine'
  args: ['npx', 'webpack', '--mode', 'production']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']

#this upload everything
#- name: 'gcr.io/cloud-builders/gsutil'
#  args: ['-m', 'cp', '-r', '*', 'gs://kahului_cloudbuild/built2']
